version: '3'

services:
  db:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    restart: unless-stopped
    container_name: db-videod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videod
    networks:
      - videod_network
    volumes:
      - videod_data:/var/lib/mysql

  app:
    image: datnguyen10102004/videod:${IMAGE_TAG:-latest}
    container_name: videod-be
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/videod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DO_ACCESS_KEY_ID: ${DO_ACCESS_KEY_ID}
      DO_SECRET_KEY: ${DO_SECRET_KEY}
      GG_CLIENT_ID: ${GG_CLIENT_ID}
      GG_CLIENT_SECRET: ${GG_CLIENT_SECRET}
      FE_URL: ${FE_URL}
      REDIS_URL: redis://redis_videod:6379
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - videod_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - videod_network
    depends_on:
      - app
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3030:3000"
    networks:
      - videod_network
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  redis:
    image: redis:7
    container_name: redis_videod
    restart: unless-stopped
    networks:
      - videod_network
    volumes:
      - redis_videod_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  vault:
    container_name: "vault"
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
    networks:
      - videod_network
    volumes:
      - vault_data:/data
    ports:
      - "8200:8200"
    restart: unless-stopped

#  otel-collector:
#    image: otel/opentelemetry-collector:latest
#    command: [ "--config=/etc/otel-config.yaml" ]
#    volumes:
#      - ./otel-config.yaml:/etc/otel-config.yaml
#    depends_on:
#      - jaeger
#    ports:
#      - "4317:4317"   # gRPC
#      - "4318:4318"   # HTTP
#    networks:
#      - videod_network
#
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"   # UI
#      - "14250:14250"   # gRPC collector
#    volumes:
#      - jaeger-data:/var/lib/data
#    networks:
#      - videod_network

volumes:
  videod_data:
  grafana_data:
  prometheus_data:
  redis_videod_data:
  jaeger-data:
  vault_data:

networks:
  videod_network:
    driver: bridge
