spring:
  application:
    name: MovieD
  datasource:
    url: jdbc:mysql://localhost:3306/videod
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GG_CLIENT_ID}
            client-secret: ${GG_CLIENT_SECRET}
  data:
    redis:
      host: localhost
      port: 6379

server:
  forward-headers-strategy: framework

fe_url: ${FE_URL:http://localhost:3001}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}

#otel:
#  metrics:
#    exporter: otlp
#  service:
#    name: videod_otel
#  traces:
#    exporter: otlp
#  exporter:
#    otlp:
#      endpoint: http://localhost:4317

do:
  space:
    bucket: videod
    region: sgp1
    url: sgp1.digitaloceanspaces.com
    access_key: ${DO_ACCESS_KEY_ID}
    secret_key: ${DO_SECRET_KEY}

jwt:
  secret-key: 'Y0doaGJXNW5kWGxsYm5SaGRHUmhkR0YwZEhReU1ESTBMakU9'
  expiredAccess: '4h'
  expiredRefresh: '1d'

logging:
  level:
    io:
      micrometer:
        core:
          instrument: DEBUG