spring:
  application:
    name: videod
  config:
    import: optional:vault://
  cloud:
    vault:
      token: root-token
      kv:
        enabled: true
      scheme: http
  datasource:
    url: jdbc:mysql://localhost:3306/videod
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GG_CLIENT_ID}
            client-secret: ${GG_CLIENT_SECRET}
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: ${profile:dev}

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}
#  tracing:
#    sampling:
#      probability: 1.0
#
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces

do:
  space:
    bucket: videod
    region: sgp1
    url: sgp1.digitaloceanspaces.com
    access_key: ${DO_ACCESS_KEY_ID}
    secret_key: ${DO_SECRET_KEY}

jwt:
  secret-key: 'Y0doaGJXNW5kWGxsYm5SaGRHUmhkR0YwZEhReU1ESTBMakU9'
  expiredAccess: '4h'
  expiredRefresh: '1d'

logging:
  level:
    io:
      micrometer:
        core:
          instrument: DEBUG
    org.springframework.cloud.vault: DEBUG